### ISSUE TITLE
Game crashes when Mekanism universal cable connects

### ISSUE THREAD

**Issue by Sippy106** [xJon/The-1.12.2-Pack#422] opened 2020-05-31 01:04 UTC
sometimes if i try to connect a mekanism universal cable my game crashes instantly. 

![minecraft crash](https://user-images.githubusercontent.com/66188908/83342052-ca66c080-a2ea-11ea-8871-0f95ff7fcd86.jpg)

i am not able to do anything and i am forced to alt+f4 the game. I wont even be able to take a screenshot, which is the reason for the bad quality picture. I think it is a client side issue, because the server console doenst show any error....I could not find anything like this before

**Comment by xJon** [comment] 2020-05-31 23:57
Please post your latest crash log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide (under `Finding crash report location`).

**Comment by Sippy106** [comment] 2020-06-01 20:29
https://paste.ubuntu.com/p/gBCgpb4g3c/ 
https://paste.ubuntu.com/p/gk89gQ26rz/
https://paste.ubuntu.com/p/CfBSw6677k/

These are my 3 latest crashes. All are caused by connecting or removing mekanism cables

**Comment by Sippy106** [comment] 2020-06-01 20:30
> Please post your latest crash log file using a [paste-tool](http://paste.ubuntu.com/).
> You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide (under `Finding crash report location`).

https://paste.ubuntu.com/p/gBCgpb4g3c/
https://paste.ubuntu.com/p/gk89gQ26rz/
https://paste.ubuntu.com/p/CfBSw6677k/

These are my 3 latest crashes. All are caused by connecting or removing mekanism cables

**Comment by xJon** [comment] 2020-06-02 11:47
Can you try to remove the VoxelMap mod and try again?

**Comment by Sippy106** [comment] 2020-06-02 22:51
Okey i tried to start the game and ran into another crash :/

https://paste.ubuntu.com/p/j4ZXm34FQB/

it tells me that something is wrong with Botania

**Comment by xJon** [comment] 2020-06-02 22:55
That is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/13#issuecomment-581057164.

**Comment by Sippy106** [comment] 2020-06-02 23:55
Thanks <3 keep up the great work mate... Its a beautiful pack ;)

**Closed** 2020-07-08 12:45 UTC
Labels: help wanted
