### ISSUE TITLE
Ender IO blocks don't render fluids (caused by VoxelMap)

### ISSUE THREAD

**Issue by ILLIODIN** [xJon/The-1.12.2-Pack#863] opened 2023-02-16 23:50 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: no

**Issue description**
Description of what help is needed.

The issue is the fluid is not appearing on multiple ender.io machines. The fluid appears in conduits fluid pipes but not inside machines for example Killer joe, Frank N Zombie generator, or a fluid tank. All of the machines are pet of Ender.Io mod including the liquid itself

**Comment by xJon** [comment] 2023-03-17 17:49
Hi and apologies for the delayed response!
What do you mean by "not appearing"? I tried putting some inside of a Fluid Tank and it seems to appear?
![image](https://user-images.githubusercontent.com/8945347/225980539-4b0c31f8-1104-452f-af26-e592f146c114.png)

**Comment by ILLIODIN** [comment] 2023-03-18 02:27
By appear I mean that it doesn't display on machines such as frank,n,zombie generators from the outside.Like the containers or machines does not display the level of liquid inside but yes or course that you are able to see it when interacting and working with the machines.

**Comment by xJon** [comment] 2023-03-18 04:05
Oh, I understand now. Can you see other liquids render properly?

**Comment by xJon** [comment] 2023-03-19 15:43
This is caused by a conflict with VoxelMap.

**Comment by xJon** [comment] 2023-03-19 16:53
As neither of the affected mods are in development, I'll close this for now, but it might get fixed in the future if a developer will look into it. Thank you nevertheless for the report!

**Closed by xJon** 2023-03-19 16:53 UTC
Labels: wontfix, minor bug, can reproduce
