### ISSUE TITLE
Getting disconnected from server when first travelling to the Moon, now cant rejoin.

### ISSUE THREAD

**Issue by Lautarosco** [xJon/The-1.12.2-Pack#944] opened 2024-03-15 03:12 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?
**yes**.
3. Are you using Java 8, 64-bit?
**yes**.

**Information required**
1. Is the modpack crashing: **It disconnects the user from the server**
2. Crash/latest log *link*

latest.log: https://pastebin.com/Yi4ARv85
latest.log (another one, got just once): https://pastebin.com/6GMSABCc
server console crash: https://pastebin.com/ZkTt73Q1

3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

My friend went to the Moon with Galactic Craft for the first time in this server and his game instantly crashed when arriving. When he tried to reconnect, he got disconnected as well. We are playing server hosted multiplayer.

**Comment by xJon** [comment] 2024-03-15 03:22
Appears to be a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/908 - As a workaround I recommend you to manually update Extra Planets as a workaround until the next modpack update. You can find it over https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4756976 and replace the older version in the `mods` folder, for both the server and clients.

**Closed** 2024-03-18 10:18 UTC
Labels: duplicate
