### ISSUE TITLE
Entity Caused Crash (NOT CULLING)

### ISSUE THREAD

**Issue by Rebecca-Se** [xJon/The-1.12.2-Pack#801] opened 2022-08-15 21:07 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **(https://pastebin.com/m0hAzrmG)**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
Upon loading the chunk in question that contains the entity from GalacticraftCore, the entire server crashes, followed by a client-side lock up.
A clear and concise description of what the issue is.

**Comment by xJon** [comment] 2022-08-15 23:16
Indeed seems like a Galacticraft crash. We're not running the latest version although I plan to update soon, could you refer this issue to the new issue repo so the devs could check it out? https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues

**Comment by xJon** [comment] 2022-09-02 19:10
As I can't verify this is not caused by additional server plugins, I will close the issue, but feel free to discuss it over the mod's repository!

**Closed by xJon** 2022-09-02 19:10 UTC
Labels: help wanted
