### ISSUE TITLE
Bees Stuck in AE2 ME System

### ISSUE THREAD

**Issue by Furry** [xJon/The-1.12.2-Pack#65] opened 2019-12-15 20:02 UTC
Basic details

Are you using a legitimate launcher and Minecraft account:
Yes
Are you using a computer with 8GB or more of RAM?
Yes
Are you using Java 8, 64-bit?
Yes
Information required

Is the modpack crashing: No
Crash/latest log: None Needed
Is Optifine installed or any other additional mods: Yes, Optifine.
Describe the issue

When working with bees on the mod Forestry, I found that many of the bees I store in my ME system are unable to be removed by hand. If you click them, nothing happens. The majority of my stored bees are like this, but there are some others I can pick up normally. Haven't noticed a trend with the bee's data, or anything like that.

This might have something to do with ticket #64, as Gendustry (an addon for Forestry) is a bit buggy as well.

**Comment by xJon** [comment] 2019-12-15 22:48
Can you get them out using an export bus + a fuzzy card?

**Comment by Furry** [comment] 2019-12-17 21:22
Sorry for the long wait, my chunk was corrupt, but I managed to replicate it somewhere else. No, the bees weren't able to be removed via export bus & fuzzy card when I tried.

**Comment by knoxog** [comment] 2019-12-18 01:15
I second this bug, but it seems to be with unstackable items falling under a metadata tree. For example "The Ender" swords from EnderIO and enchanted books. It's not every item though, say you have 15 unique enchant books in your ME; 5-10 of them will give you a problem with taking them out of a terminal

**Comment by Furry** [comment] 2019-12-18 02:12
Yikes, that doesn't sound like an easy fix.. #72 is looking p'nice right about now xD

**Comment by xJon** [comment] 2019-12-18 19:50
Try to follow this guide written by VT-14:
> 1. Use an ME Chest to figure out what Storage Cell it is on. 
> 2. Set up an isolated system (use Quartz Fiber to transfer only power from your main network) with an ME IO Port and an ME Storage Bus connected to a Chest (or any other inventory block, like a Storage Chest, Iron Chest, etc.).
> 3. Put the Storage Cell in the IO Port, and set it to send items from the drive to storage if necessary (that's the default). It will then try to pull all items off of the Storage Cell and put them into storage (which, on this separated system, is only the chest).
> 4. Keep emptying the Chest until you get your /Dank/Null back. Return the Storage Cell and put the other items back into your ME System.

**Comment by HugoZink** [comment] 2019-12-19 23:10
This is an old bug in AE2 that they *refuse* to fix. Very annoying.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3756

AE2 blames it on Forge and vice-versa, getting pack developers and players absolutely nowhere. Use an export bus with a fuzzy card and make sure it matches the stuck bee as closely as possible.

It's an itemstack mismatch between server and client apparently.

**Comment by Furry** [comment] 2019-12-21 19:43
This happens with Extra Utilities 2 Generators as well..

**Comment by xJon** [comment] 2019-12-22 10:42
I can't reproduce it in a new ME system, but this will just stay as a `wontfix` until AE2 can do something about it.

**Closed by xJon** 2019-12-22 10:42 UTC
Labels: #don't_blame_the_modpack, minor bug, wontfix
