### ISSUE TITLE
Forestry mutifarm structures

### ISSUE THREAD

**Issue by Averixia** [xJon/The-1.12.2-Pack#420] opened 2020-05-27 16:20 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **No**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: **No**

**Describe the issue**

I have used forestry multiblock farms in the past, and decided to revisit them.  I have managed to create a 3x4x3 and a 4x4x4, and both times, even though the farms were working as designed, you are unable to bonemeal/fertilise a sapling place on the humus, and saplings will not grow on humus on a farm structure.  I have recreated this in a creative world as well, and have tried this in different biome with the same result.  The server has been restarted, as well as the structure both time, but still this hasn't solved this issue.

![2020-05-27_17 17 40](https://user-images.githubusercontent.com/66026689/83046028-4d172380-a03e-11ea-92c2-18cfaae6b168.png)
![2020-05-27_17 17 45](https://user-images.githubusercontent.com/66026689/83046033-4e485080-a03e-11ea-9dab-9a4270399fc4.png)
![2020-05-27_17 18 14](https://user-images.githubusercontent.com/66026689/83046037-4ee0e700-a03e-11ea-93c7-84d9adf0e03d.png)

**Comment by Raxcental** [comment] 2020-05-27 16:44
I have experienced the same issue. I've found that the arboretum machine works wonders. It also looks nicer. It requires mostly the same stuff too. Water, Power, Dirt, and Saplings.

**Comment by Averixia** [comment] 2020-05-27 20:48
Small update, looks like it might only be oak saplings not spawning right.  They seem to produce mishapen trees if/when they do grow.  Spruce saplings seem to be okay.

**Comment by xJon** [comment] 2020-05-28 14:39
What do you mean by misshapen trees?

**Comment by Averixia** [comment] 2020-05-28 15:14
Like this.  There are no 'normal' style of oaks spawning on it at all.


![2020-05-28_16 12 43](https://user-images.githubusercontent.com/66026689/83159823-55cf2e80-a0fe-11ea-9de5-2d271ae5c889.png)
![2020-05-28_16 13 44](https://user-images.githubusercontent.com/66026689/83159828-5798f200-a0fe-11ea-9123-843f33fd5fa2.png)

**Comment by xJon** [comment] 2020-05-30 18:53
I see. This is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/325, which will get fixed in the next modpack update.
See [this](https://github.com/xJon/The-1.12.2-Pack/issues/325#issuecomment-610515780) comment for the fix.

**Closed by xJon** 2020-05-30 18:53 UTC
Labels: help wanted
