### ISSUE TITLE
Apocrypha Lost Magic Unlock Failing

### ISSUE THREAD

**Issue by Satvn** [xJon/The-1.12.2-Pack#875] opened 2023-04-10 20:13 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes 

2. Are you using a computer with 8GB or more of RAM? 
yes

3. Are you using Java 8, 64-bit? ([How to check]
Yes

**Information required**
1. Is the modpack crashing: No
3. Is Optifine installed or any other additional mods: No

**Describe the issue**
(I believe Apocrypha may come under the mod “Reforbidden magic” as that is what shows in JEI)

Apocrypha on older versions 1.5.2 and below always failed to allow the player to complete the starting research for the mod “Lost Magic”. This has appeared in a bunch of posts online about the same problem with the mod. 

On a fresh SP world in 1.5.4 with fresh thaum research, this was not an issue and I could immediately complete Lost magic and proceed to the next mod research.

On a Server running 1.5.4 (that was on 1.5.2 before) I was still unable to complete the research.  I also tested with a player who had never touched thaumcraft and they could not research the Lost Magic page either.  I’m not able to test in a fresh 1.5.4 server at current 

I booted the pack in version 1.5.2 and made a new SP world and started fresh thaum research. The Lost magic research failed to complete. On changing the pack to 1.5.4 the research could be completed in the previously 1.5.2 world

It seems this is is only an issue in servers that updated and the issue is solved in single player regardless.

**Comment by xJon** [comment] 2023-04-10 20:24
Apocrypha in 1.12.2 was originally only featured by a mod called Lost Magic, which brings _some_ features from Forbidden Magic (which originally was a 1.7.10 mod). It had a bug that broke research in all versions of the modpack under `1.5.3` (which updated the mod for the fix after reporting it to the author).
That being said, in `1.5.3` another mod called ReForbidden Magic added, which brings back _all_ (or, the rest) of the features from 1.7.10.
This means I'm not sure whether this issue is caused by Lost Magic or ReForbidden Magic.
Is there any chance you could test whether removing ReForbidden Magic resolves the issue (with the cost of removing some features)? Then we'll be able to know which mod author to ask regarding this issue.

**Comment by Satvn** [comment] 2023-04-10 20:29
The issue seems to be only a server side issue now, seems to be patched in SP. Though I don’t have the ability to test with putting up servers right now, so if anyone is able to make a fresh server with version 1.5.4 or remove the mods you mentioned to remove on a pre-existing server that would be help.

**Comment by xJon** [comment] 2023-04-10 20:34
I'll test a fresh `1.5.4` server, although I'm not sure if I can reproduce your exact situation upgrading a progressed `1.5.2` world to `1.5.4`.

**Comment by Satvn** [comment] 2023-04-10 20:38
If the issue is resolved on a fresh server then It may just require manually giving players research on updated servers

**Comment by xJon** [comment] 2023-04-10 20:55
That's a good point.
I just tested a fresh server and the issue is not apparent - it behaves the same as singleplayer and unlocks it upon progressing to the Thaumonomicon!
![image](https://user-images.githubusercontent.com/8945347/230997147-3368e9fc-0745-42d8-b8d4-d7d02843f0b1.png)

**Comment by Satvn** [comment] 2023-04-10 21:33
Hm, in that case I’m not sure what way there would be a way to fix this on updated servers as realistically the issue is solved other than manually giving users that wanted the research progression through the available thaum commands

**Comment by xJon** [comment] 2023-04-10 21:36
@SpitefulFox Do you believe that https://github.com/SpitefulFox/LostMagic/commit/ab92680b71c69e2f018bc725a129211ae3b4c33a resolved the unlocking issue (https://github.com/SpitefulFox/LostMagic/issues/5) but only for new saves?

**Comment by xJon** [comment] 2023-04-22 18:37
Will close this for now as it does seem to only affect existing worlds. If someone has upgraded from an older version, please manually research it using `/thaum research`.

**Closed by xJon** 2023-04-22 18:37 UTC
Labels: wontfix, mod issue, minor bug, workaround available
