### ISSUE TITLE
Game crashes when I go to the Moon with Dark Steel Armor equipped.

### ISSUE THREAD

**Issue by MegaPiggy** [xJon/The-1.12.2-Pack#917] opened 2023-10-06 00:25 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? :
**yes**.
3. Are you using Java 8, 64-bit? :
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log
[crash-2023-10-05_19.32.30-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/12825730/crash-2023-10-05_19.32.30-server.txt) 
[latest.log](https://github.com/xJon/The-1.12.2-Pack/files/12825731/latest.log)
https://mclo.gs/LRHyR3o

4. Is Optifine installed or any other additional mods: **yes**

**Describe the issue**

When I launch my rocket to the moon and get out with any of EnderIO's dark steel armor equipped (ex. Dark Helm, Dark Plate, Dark Leggings, and Dark Boots) the game will crash as soon as I get out of the space lander. 
Obviously the issue was that I wasn't wearing a spacesuit, but either way it still shouldn't crash if i don't have one.
The main mod that causes this error is Extra Planets.

Here's a video of when I first encountered this error.

https://github.com/xJon/The-1.12.2-Pack/assets/34462599/f2e55410-bb6a-4ba0-b681-0f1c446b0740

**Comment by xJon** [comment] 2023-10-06 04:02
I believe this is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/908.

**Comment by MegaPiggy** [comment] 2023-10-15 05:56
yeah it was. latest update of extra planets fixed it.

**Closed** 2023-10-15 09:27 UTC
Labels: duplicate
