### ISSUE TITLE
Locked out from Server by Crashes

### ISSUE THREAD

**Issue by NietzscheKadse** [xJon/The-1.12.2-Pack#928] opened 2023-11-19 17:39 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): [**link to paste**](https://pastebin.com/PhFdYQvH)
2. Is Optifine installed or any other additional mods: **no** 

**Issue description**
I created a Space Station (Flying up there with a Tier 1 Rocket, 3 Chests so 50-something storage spaces). Once the Dimension (3) loaded it kicked me from the server.
I now can't join the server because I always try to join, see the space + my Interface for a split-second and then it just disconnects me with "Internal Server Error". In the log you can see multiple login attempts from me.
Something that could have something to do with it is, that I flew up there with a oxygen mask, oxygen system but without connected oxygen tanks. The Tanks are in my Inventory but I forgot to equip them.

**What I tried**
- Server Restart
- Client Restart
- Op-ing a friend so he gives me Gamemode 1 the second my join message appears in chat

I would appreciate any help.

**Comment by NietzscheKadse** [comment] 2023-11-19 18:07
I got myself back into the overworld by using the split second I join to use the console and teleport me to  ~ ~-100 ~ which put me back into the overworld.

When I go back to the Space Station now, I still get the same problem though. But ONLY when I am in survival mode.
In Gamemode 1 I can normally be in the Space Station Dimension. In Gamemode 0 I get kicked and can't join again, even if I switch it up there.

**Comment by xJon** [comment] 2023-11-20 15:53
This is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/908, I'd recommend you in the meantime to manually update the Extra Planets mod :)

**Comment by xJon** [comment] 2024-04-12 02:06
Closing due to inactivity.

**Closed by xJon** 2024-04-12 02:06 UTC
Labels: duplicate
