### ISSUE TITLE
AKASHIC TOME crash (with Traveler's Notebook)

### ISSUE THREAD

**Issue by scar0002** [xJon/The-1.12.2-Pack#925] opened 2023-11-09 22:06 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: yes
**no / yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**. yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**no / yes**. yes

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yes (list) / no**  yes but not for this mod

**Issue description**
Description of what help is needed.
Whenever I open the AKASHIC TOME and press the creating a portal for the twilight forest it crashes and im not to sure why i have no idea how to create this portal and cant find any help online , i would like to continue this world but now there isnt allot for me to do. What do i do to stop the AKASHIC TOME from crashing my whole game?

**Comment by xJon** [comment] 2023-11-09 23:34
Thanks for the report! This is caused by https://github.com/jbredwards/Fluidlogged-API/issues/186 and will be resolved in the next modpack update.

**Comment by scar0002** [comment] 2023-11-09 23:43
Okay Thank you :)

**Comment by xJon** [comment] 2024-04-12 21:47
This should be resolved in `1.5.6`.

**Closed by xJon** 2024-04-12 21:47 UTC
Labels: mod issue, minor bug
