### ISSUE TITLE
Kicked from aternos 1.12.2 server when goes to the moon in survival mode

### ISSUE THREAD

**Issue by Kas2004** [xJon/The-1.12.2-Pack#933] opened 2024-01-02 22:03 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**no**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
2. Is Optifine installed or any other additional mods: **yesno** 

**Issue description**
Description of what help is needed.
Get onto the moon in survival

**Comment by xJon** [comment] 2024-01-02 22:34
This is most likely a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/908, you can either manually update the mod or not use your modular powersuit when going to space.

**Comment by xJon** [comment] 2024-04-12 02:07
Closing due to inactivity.

**Closed by xJon** 2024-04-12 02:07 UTC
Labels: duplicate
