### ISSUE TITLE
Logistics Pipes client crash

### ISSUE THREAD

**Issue by AngryCarrot789** [xJon/The-1.12.2-Pack#816] opened 2022-09-14 19:12 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: **yes**.
2. Are you using a computer with 8GB or more of RAM?: **yes**.
3. Are you using Java 8, 64-bit?: **yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. Crash/latest log:
The crash report: https://mclo.gs/C6oKT82
I think foam fix is what stops your game exiting and gives you the option to "go back to the main menu", i get pretty much the same crash report when I click that button
From the looks of it, it looks like something is concurrently modifying an ArrayList in LoliASM's FramesTextureData (on another thread most likely)

4. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
I created a 3x3 ring using ME controllers which also had a wireless access point on the top, and my game just froze (didn't get a crash report; screen went light blue). When i joined back, i connected my power to the ME controller ring and i got the crash report above. When i clicked "Go back to main menu", the game kept showing the same crash report screen

**Comment by xJon** [comment] 2022-09-14 19:14
Can you please send over your entire client log using https://mclo.gs/ ?

**Comment by AngryCarrot789** [comment] 2022-09-14 19:18
I put it in the main post: https://mclo.gs/C6oKT82

**Comment by xJon** [comment] 2022-09-14 19:18
@AngryCarrot789 That's the crash log, I mean the `latest.log` from the session you experienced the crash

**Comment by AngryCarrot789** [comment] 2022-09-14 19:21
Ah right: https://mclo.gs/E3Y5B6w

**Comment by xJon** [comment] 2022-09-14 19:23
Seems to be caused by Logistics Pipes. Can you reproduce this crash? If so, can you try out this [new version of Logistics Pipes](https://www.curseforge.com/minecraft/mc-mods/logistics-pipes/files/3989571)?
Also, do you have Logistics Pipes placed in your world?

**Comment by AngryCarrot789** [comment] 2022-09-14 19:26
I do use logistics pipes, but I placed them around 150 blocks away from my main base in order to reduce FPS lag when at my base. It looked it was a security station, so i removed it for now (i don't use it much). And i could try the new LP version, but i play on a server so i'm not sure if it will let me play if the version is different

**Comment by xJon** [comment] 2022-09-14 19:27
Yeah that's okay. I'll mark it as a minor issue for now, although it might take a while to fix. Thanks for the report nonetheless!

**Comment by AngryCarrot789** [comment] 2022-09-14 19:29
This is my setup if it helps: screen is facing north-west, on the west side is the security station, north side is a quantum entangleoporter for transfering items
![image](https://user-images.githubusercontent.com/32274404/190244973-61734b3d-fac8-4204-88fa-b2dec828bef0.png)

**Comment by xJon** [comment] 2022-09-14 19:30
Thank you! I'll forward this to the developer :)

**Comment by xJon** [comment] 2022-09-14 19:32
@AngryCarrot789 If you can reproduce this issue on a singleplayer world, testing the new version I sent you might be useful for future reference :)

**Comment by xJon** [comment] 2022-11-05 21:41
This should be resolved in `1.5.2`!

**Closed by xJon** 2022-11-05 21:41 UTC
Labels: mod issue, minor bug
