### ISSUE TITLE
Applied Energistics Terminal shuts down for a second while putting stacks of items into ME system

### ISSUE THREAD

**Issue by treknib** [xJon/The-1.12.2-Pack#233] opened 2020-02-24 15:15 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: ** no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **n/a**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Using a ME Crafting Terminal (others not tested) and double click a stack of items in my inventory using shift+doubleclick to put multiple stacks of that item from my inventory into the ME system, the terminal will gray out for a second, and only 1-3 stacks are transfered instead of all stacks.

![ME_bug_01](https://user-images.githubusercontent.com/13683332/75164062-7a42f580-5720-11ea-81d9-f59740ad7702.jpg)
![ME_bug_02](https://user-images.githubusercontent.com/13683332/75164071-7f07a980-5720-11ea-94fe-a2c5273ff96e.jpg)

**Comment by xJon** [comment] 2020-02-24 17:42
Does it have enough power?

**Comment by Furry** [comment] 2020-02-25 17:21
That's usually a power issue, are you using an energy acceptor or controller?

**Comment by ItsBurn2020** [comment] 2020-02-26 18:00
i have the same issue but it is not bothering me. I have a power acceptor ant it goes directly to a power cube the dense one and the in to the controller and after that all spreads around the base

**Comment by xJon** [comment] 2020-03-01 12:24
Try to add an energy cell to the side of the acceptor, to increase the ME system power buffer.

**Comment by HugoZink** [comment] 2020-03-11 10:34
This is not a bug, this is just what happens when you don't have a big enough power buffer.

ME Controllers can hold a little bit of reserve energy, but Energy Acceptors can hold **none**. Add an energy cell to the network, and this issue should be fixed.

**Comment by xJon** [comment] 2020-03-23 18:26
Closed due to inactivity.
Will reopen if requested.

**Closed by xJon** 2020-03-23 18:26 UTC
Labels: help wanted
