### ISSUE TITLE
Project GLASS mod

### ISSUE THREAD

**Issue by MilkSyrup31** [xJon/The-1.12.2-Pack#437] opened 2020-06-09 07:31 UTC
i feel like the Project GLASS mod should be added, i think it would fit in with the modpack.

**Comment by xJon** [comment] 2021-01-14 02:11
Duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/30, thank you for the suggestion nonetheless and feel free to add it yourself manually!

**Closed by xJon** 2021-01-14 02:11 UTC
Labels: duplicate
