### ISSUE TITLE
Botania Manapool Bug

### ISSUE THREAD

**Issue by jajajafeti** [xJon/The-1.12.2-Pack#463] opened 2020-06-30 22:22 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM?:
**yes**.
3. Are you using Java 8, 64-bit?:
**yes**.

**Information required**
1. Is the modpack crashing: **yes**
2. latest log
--> from Video: https://paste.ubuntu.com/p/F3cdqKxf9f/
    I had to cut it down

I also have a log from the reconnect crash, which I also cut down
--> bug happens at 23:51: https://paste.ubuntu.com/p/nkYZkDWnSR/

3. Is Optifine installed or any other additional mods: **no** (I use the pack in its default)

**Describe the issue**
First watch the Video so you know what I am talking about... (like and subscribe xD)
Here is a Video of how I recreated it
--> https://www.youtube.com/watch?v=AJnGLCttbMU

Its kinda complicated, I first noticed it, when I was on this platform in the Sky for a longer time. Then I went down, and the server (playing with a friend) started lagging, fps dropped to 1. And eventuall I lost the connection. If I then reconnect I spawn at a wrong location and I get disconnected imediately. After a few tries, it works. So i got this every damn time when I stayed some minutes on the platform in the sky. So I investigated and mined everything on the platfrom and without the Manapools from Botania it did not happen again.
As you see in the Video I discovered to easily trigger it like that, but normaly I get back to the Title screen and dont crash completely.

So its not a major Problem for me, caus I dont use Botania that frequent, but I think it has something to do with the hight.
I havent tested what happens if I do the same on the Ground.... maybe I update on that later.

Good Night

**Comment by xJon** [comment] 2020-07-01 10:19
This is most likely a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/13, but thank you anyway for reporting!

**Closed by xJon** 2020-07-01 10:19 UTC
Labels: duplicate
