### ISSUE TITLE
Ships waterlogged since new 1.5.5 update?

### ISSUE THREAD

**Issue by Pocketkid2** [xJon/The-1.12.2-Pack#916] opened 2023-10-02 05:28 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: **yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)): **yes**
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): **yes**

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **N/A**
3. Is Optifine installed or any other additional mods: **Storage Drawers, Building Gadgets, Flans mod, Dynmap**

**Describe the issue**

My friends and I have a server we started on modpack version 1.5.4. We recently upgraded to version 1.5.5, with the same world, and found that newly generated ships (both the giant ships and the small pirate ships) are now waterlogged at the waterline. This also occurs in newly generated single player 1.5.5 worlds. (i.e. this is a reproducible bug)

This is extremely annoying because it means that we can no longer explore the bottom storage deck of the giant ships, because they are completely underwater, and it makes the deck above that (with the beds) difficult to traverse.

Any ideas what's going on here? We didn't change anything other the version. We have a few other mods but we don't think those are the problem, although we could test. We also don't know if other structures are affected because the ships are the ones that sit in the ocean below the waterline.

**Comment by xJon** [comment] 2023-10-02 15:20
If you change `fluidloggedFluidSpread:` to `1` inside of `\config\fluidlogged_api.cfg`, if the issue is still present when generating new ships?

**Comment by Pocketkid2** [comment] 2023-10-02 19:34
I changed `fluidloggedFluidSpread` from 2 to 1, started the server, teleported far out into the wilderness where chunks had not been generated yet, and the first ship I found still has the waterlog issue. Should I try setting the value to 0?

**Comment by xJon** [comment] 2023-10-02 20:11
Yes, that'd be useful testing. Also just to clarify the config should be changed on the server-side.

**Comment by Pocketkid2** [comment] 2023-10-02 22:46
Yep, I tried `fluidloggedFluidSpread` as both 1 and 0 on the server folder, booted it up, explored some newly generated chunks, and the ships are still waterlogged. Not sure what the deal is.

**Comment by xJon** [comment] 2023-10-03 00:54
Can you try to reproduce by completely disabling the Fluidlogged API mod file?

**Comment by sashieplays** [comment] 2023-10-03 18:13
I fixed the issue be simple deleting the Fluidlogged API mod

**Comment by Pocketkid2** [comment] 2023-10-05 00:36
I can confirm that removing the Fluidlogged API mod fixes the problem

**Comment by xJon** [comment] 2024-04-12 21:47
This should be resolved in `1.5.6` as Fluidlogged API was removed.

**Closed by xJon** 2024-04-12 21:47 UTC
Labels: mod issue, minor bug, workaround available
