### ISSUE TITLE
Backups failing 

### ISSUE THREAD

**Issue by blast169** [xJon/The-1.12.2-Pack#242] opened 2020-02-27 21:26 UTC
1. Are you using a legitimate launcher and Minecraft account:
Yes, Twitch
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

1. https://paste.ubuntu.com/p/FvMCtxcyXB/
2. Is Optifine installed or any other additional mods: No

Description of what help is needed.
Singleplayer, backups are failing, when I try to manually do the backups (/backupsmod backup) they still fail as well, message reads "Backup failed! Check log for more details", they were working fine a few days ago

**Comment by xJon** [comment] 2020-02-28 14:12
Duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/227.
> I asked the mod author and he recommended you to try to delete the file `backups\REDRED\Last`.

The author said he will hopefully implement fixes to prevent this from happening in the future.

**Closed by xJon** 2020-02-28 14:12 UTC
Labels: help wanted
