### ISSUE TITLE
AE2 Autocrafting  System refuses to craft IC2 generator.

### ISSUE THREAD

**Issue by Raxcental** [xJon/The-1.12.2-Pack#411] opened 2020-05-21 07:58 UTC
1. Are you using a legitimate launcher and Minecraft account:
Yes

2. Are you using a computer with 8GB or more of RAM?:
Yes (16 total, 7 allocated) 

3. Are you using Java 8, 64-bit?:
Yes

1. Crash/latest log: 
Not Applicable

2. Is Optifine installed or any other additional mods:
None

Description of what help is needed.

My ME autocrafting system refuses to craft an IC2 generator, even if all the components are already in the system.

To be clear, the system will craft anything else I tell it too. It will craft all the generator components. It will request processing from furnaces and macerators. It just refuses to craft the IC2 generator. Which puts a stop to autocrafting solar panels.

I have 5 crafting Coprocessors, 2 64k crafting storage, 3 crafting monitors. So there shouldn't be an issue there. And again. All the components are already in the system, it just refuses to craft with them and the generator is stuck in Scheduled status indefinitely.

**Comment by Raxcental** [comment] 2020-05-23 04:46
I tried using an external machine to craft the generator and only had the ME system provide the parts, it still refused to even do that. There seems to be not way to autocrafting a generator. And it's only that item that I have a problem with.

**Comment by xJon** [comment] 2020-05-25 12:09
This is unfortunately a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/169#issuecomment-578457147, a known issue with AE2.

**Closed by xJon** 2020-05-25 12:09 UTC
Labels: help wanted

**Comment by Raxcental** [comment] 2020-05-25 19:11
Ah. Okay. Thank you.
