### ISSUE TITLE
FastWorkbench frequently causes registry desync for players

### ISSUE THREAD

**Issue by Rishum-P** [xJon/The-1.12.2-Pack#758] opened 2021-12-27 14:35 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): 
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Ever since FastWorkbench was added to the pack, players have been constantly getting the following error (registry desync) when connecting to multiplayer servers:

![Capture](https://user-images.githubusercontent.com/21267720/147479021-3ccb333c-27be-4553-af13-9a355a52a49f.PNG)

This issue has been experienced by a significant amount of players and has been a common issue in the 1.12.2 pack tech-support discord channel for a while now. Typically the issue can be resolved by the player's fully reinstalling the pack, but this does not in all instances solve the problem. Removing the mod from both the client + server does appear (in my limited testing) to fix the issue, though it's not ideal.

This issue has also been previously described here: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1592 (though not all of it is accurate)

Rokk stated in Discord that this issue is so frequent that they believe mod should be removed from the the pack. I am inclined to agree, even with the negative performance impact it will have. For MC 1.16 there is: https://www.curseforge.com/minecraft/mc-mods/fastworkbench-minus-replacement which solves this issue (by correctly not using replacement), perhaps if this is downported in the future it could be included in the pack instead.

**Comment by xJon** [comment] 2022-10-28 16:27
Currently it seems that it is caused by some file corruption on client or server side, but that might be caused due to FastWorkbench.
@Rongmario told me this might be addressed in the next version of https://github.com/LoliKingdom/LoliASM/, including its own implementation.

**Comment by xJon** [comment] 2022-11-05 21:43
Closing for now.

**Closed by xJon** 2022-11-05 21:43 UTC
Labels: wontfix, minor bug, workaround available

**Comment by xJon** [comment] 2023-04-05 03:28
Should not occur anymore in `1.5.3` and above due to the removal of Fast Workbench (for Universal Tweaks' alterative method).
