### ISSUE TITLE
Crash when viewing a certain area

### ISSUE THREAD

**Issue by macgyver7575** [xJon/The-1.12.2-Pack#313] opened 2020-04-01 12:40 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account: YES
**no / yes**.
2. Are you using a computer with 8GB or more of RAM?  YES
([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**no / yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)): YES
**no / yes**.

[crash-2020-04-01_08.19.44-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/4415077/crash-2020-04-01_08.19.44-client.txt)

**Information required**
1. Is the modpack crashing: yes - client side
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link to paste**
3. Is Optifine installed or any other additional mods: NO optifine but yes additional mods:
additoinalenchantedminer-1.12.2-12.3.5-universal
davincisvessels-1.12-6.340-full
DimensionalDoors-3.0.9-287
movingworld-1.12-6.342-full
reforged-mod-1.12
veinminer-1.12-0.38.2.647+b31535a

**Describe the issue**
There are two places that we know of in our world where when anyone comes across it their client crashes stating BOTANIA is the issue.  I have attached the crash report.

A clear and concise description of what the issue is.

**Comment by macgyver7575** [comment] 2020-04-01 19:47
From what i've been researching it's a known bug between voxelmap and Botania.  How do i go about removing Botania?  I tried just dragging the Botania.jar out, but my server errors stating it's missing registry entries.

**Comment by macgyver7575** [comment] 2020-04-01 21:45
I removed voxelmap and the problem seems to have gone away.  Just that, i need a map and markers still... 

running latest version 1.1.2 of the mod

**Comment by macgyver7575** [comment] 2020-04-01 22:30
Added Journey map, players seem somewhat happy. We all liked Voxelmap better but given the client side crashes, agree to compromise.

**Comment by xJon** [comment] 2020-04-02 17:00
Yes, this is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/13.

**Closed by xJon** 2020-04-02 17:00 UTC
Labels: duplicate
