### ISSUE TITLE
Recommendation for a superb mod

### ISSUE THREAD

**Issue by pixelking1** [xJon/The-1.12.2-Pack#47] opened 2019-12-10 04:31 UTC
1. Has someone suggested this mod before: **no**
2. Why should the mod be added: Witchery was a great mod in the previous 1.7.10 modpack, i think everyone can agree? Even to those who don't, the mod **Bewitchment**, which is labeled as the successor to Witchery, which I agree with. It's a great mod and it includes the best parts of Witchery with minor lovable changes. Please Consider.

**Mod info & download page**
* Link to official page: https://www.curseforge.com/minecraft/mc-mods/bewitchment

**Comment by Furry** [comment] 2019-12-10 20:14
Bewitchment was in a previous Recommendation, and to my knowledge was closed on the basis of it being too unstable, as well as not having enough to contribute to the modpack. We all miss Witchery, but bewitchment hasn't become a viable replacement yet.

**Comment by xJon** [comment] 2019-12-10 21:10
@Furry wrote it correctly (duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/27).
Thank you nonetheless for the suggestion and hopefully soon we'll have a good replacement.

**Closed by xJon** 2019-12-10 21:10 UTC
Labels: duplicate, suggestion
