### ISSUE TITLE
Binnie's Extra Trees

### ISSUE THREAD

**Issue by ChaosKronorium** [xJon/The-1.12.2-Pack#11] opened 2019-12-01 11:19 UTC
When I right click the juniper leaves they keep giving me Juniper and when I eat them they give nothing to hunger

**Comment by xJon** [comment] 2019-12-02 01:53
Where is this happening?
I cannot reproduce this issue on my end.

**Comment by ChaosKronorium** [comment] 2019-12-02 06:24
https://drive.google.com/open?id=1PPebWU8DLcE_Vma65C59-0ZnU0o4QCLC\
Thats a clip of it

**Comment by xJon** [comment] 2019-12-02 16:31
Is this a multiplayer server?

**Comment by ChaosKronorium** [comment] 2019-12-03 00:40
No its a Single player world

**Comment by xJon** [comment] 2019-12-03 15:20
Does it still happen to you if you "cheat" the tree & berries with bone meal?

**Comment by ChaosKronorium** [comment] 2019-12-04 01:05
When I right click with bone meal nothing happens

**Comment by xJon** [comment] 2019-12-04 10:23
You need to right click the sapling with bone meal, then right click the leaf blocks with berries with bone meal.

**Comment by ChaosKronorium** [comment] 2019-12-05 08:50
Do you mean the shrub?

**Comment by xJon** [comment] 2019-12-05 11:56
Yes

**Comment by ChaosKronorium** [comment] 2019-12-06 02:21
yeh didn't do anything

**Comment by clienthax** [comment] 2019-12-09 04:41
https://github.com/ForestryMC/Binnie/issues/624

**Comment by xJon** [comment] 2019-12-15 17:39
Will update the modpack with the fix as soon as the mod resolves the issue.

**Comment by Xitoboy9** [comment] 2019-12-25 22:30
I've had this exact same thing happen to me with naturally generated cranberry leaves from Binnie's Extra Trees. Might be an issue on Binnie's side though.

**Comment by xJon** [comment] 2020-01-06 00:17
Closing for now and will stay with `wontfix` until mod dev does something about it.

**Closed** 2020-02-25 17:11 UTC
Labels: can reproduce, fixed
