### ISSUE TITLE
Bugged/Broken Textures

### ISSUE THREAD

**Issue by whoslinny** [xJon/The-1.12.2-Pack#911] opened 2023-09-07 11:58 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **https://mclo.gs/7H7whZ0**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Modpack has been reinstalled about 3 times or so, textures are always buggy and broken. This includes all blocks and all items. This is not the case for stuff like entities (players and mobs) and entity blocks (chests). Using the Prism Launcher and installed from the modpack from the Technic section. Pictures below show the broken textures:
![image](https://github.com/xJon/The-1.12.2-Pack/assets/109823394/39235f8a-3c73-4897-841e-8d5af266e716)
![image](https://github.com/xJon/The-1.12.2-Pack/assets/109823394/b9e92e86-75a5-4afb-a682-3ad3312349b1)

**Comment by xJon** [comment] 2023-09-07 12:40
Weird. I'll take a couple of guesses:
- Does it happen when you use the Technic or CurseForge launchers?
- Does it happen if you manually remove the `censoredasm5.14.jar` mod?
- Does it happen if you manually remove the `vintagefix-0.3.1-139.jar` mod?

**Comment by whoslinny** [comment] 2023-09-07 18:29
I figured it out! It was VintageFix. Thank you so much.
![image](https://github.com/xJon/The-1.12.2-Pack/assets/109823394/1a87c8dd-3864-4027-b9a8-f74c0b0a3699)
![image](https://github.com/xJon/The-1.12.2-Pack/assets/109823394/d03c9c7f-6e40-4353-8b54-07388d961808)

**Comment by xJon** [comment] 2023-09-07 18:39
@whoslinny Glad you found out the cause! And if you removed VintageFix, you probably want to add [FoamFix](https://www.curseforge.com/minecraft/mc-mods/foamfix-optimization-mod/files/3973967) in the meantime for better performance. Hopefully it will be resolved with VintageFix at the end though.

**Closed** 2023-09-07 19:48 UTC
Labels: help wanted
