### ISSUE TITLE
Thaumic Energistics Terminals no longer function as intended

### ISSUE THREAD

**Issue by Satvn** [xJon/The-1.12.2-Pack#957] opened 2024-06-03 20:04 UTC
### Was this bug reported before?

- [X] No, it was not.

### Please describe the issue you are experiencing

Since updating to 1.6.1 my thaumic energistics arcane and essentia terminals no longer function as they did on 1.5.6, the arcane terminal's ordering button simply doesn't work the first time around, and will reset back to A-Z every time you reopen the terminal, I also had an issue that stopped me from taking any items out of it at one point but that has since stopped and i dont know what caused it.
![2024-06-03_20 59 57](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/64d2e73d-f755-4f08-abff-f3dd939768ac)
![2024-06-03_21 00 00](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/afd42f2c-68f8-4341-a57f-090311519ead)
The essentia terminal no longer allows you to extract essentia with phials or jars making it quite problematic for setting up filters and research components 
![2024-06-03_20 59 49](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/d226ccfa-75ed-4c29-9c57-970cbc185bfc)
![2024-06-03_21 00 13](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/dcc1acbf-8230-481c-9c45-5f7c138235a2)

**Comment by xJon** [comment] 2024-06-03 20:18
This is most likely due to updating AE2 and Thaumic Energistics, although they were supposed to work well together.
Can you check if manually updating Thaumic Energistics to[ `2.3.1`](https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.1) resolves this? If not, can you please report this bug directly to the author over https://github.com/Delfayne/ThaumicEnergistics/issues ?

**Comment by xJon** [comment] 2024-06-03 20:23
Also, are you playing on a modified server (i.e. with plugins)?

**Comment by Satvn** [comment] 2024-06-03 20:57
I do play on a server with plugins, however i quickly tested in SP as well and the same issues are apparent, I will try boot with 2.3.1 energistics to see if the issue still remains, my latest log however doesnt have anything whatsoever when interacting with the terminals

**Comment by xJon** [comment] 2024-06-03 22:23
It appears reproducible with `2.3.1` also outside of the modpack environment, so I've reported it directly to the author myself over https://github.com/Delfayne/ThaumicEnergistics/issues/42.

**Comment by Delfayne** [comment] 2024-07-02 07:24
My apologies, these were broken as part of a series of optimisation fixes migrating several parts of ThE code to be more similar to AE2, especially item sorting and packet handling.

The end result is that the slow-ass Arcane Terminal should be a LOT faster when it has access to a large inventory.

I had had reports of bugs, which is why this version was not released to Curseforge yet. Apologies for the rough pre-release version

**Comment by xJon** [comment] 2024-07-03 00:54
Reopening this as I believe the issue is still not fully resolved in `1.6.2` (using Thaumic Energistics EL `1.3.2`).

**Comment by Satvn** [comment] 2024-07-03 18:20
The essentia terminals work now in 1.6.2! both phials and jars can take out essentia! (with 1.3.2 Thaum Energistics)

The arcane terminal is still broken though, the sorting button doesnt work as before, and items cant be pulled from it, though i did notice as i had console open that it produces this error
[errorlog.txt](https://github.com/user-attachments/files/16089174/errorlog.txt)
interestingly it mentions extracells mekanism gas, something not included in the ME network (i used a single AE2 unofficial extended life 1k storage cell)

**Comment by Delfayne** [comment] 2024-07-04 21:51
btw it's 2.3.x of ThE, not 1.3.x
This error can occur because Gas AE is installed at all, not that you're currently using cells. I'll harden the checks in ThE to prevent that.
Unsure why the sorting is broken but I can play with it some more and see if I can reproduce it. 

The sorting behaviour from before did need to change though. It was extraordinarily laggy in large systems to where the UI was unusable. Just gotta smooth out the problems.

**Comment by Delfayne** [comment] 2024-07-07 00:46
Both bugs should be fixed now

**Closed** 2024-07-11 01:12 UTC
Labels: fixed
