### ISSUE TITLE
Chisels & Bits issue with 1.5.5

### ISSUE THREAD

**Issue by andoraspalace** [xJon/The-1.12.2-Pack#907] opened 2023-09-03 13:53 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: ** no**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**
When chiseling glass with "Chisels & Bits" the glass turns into a not transparent block!
![2023-09-03_15 52 22](https://github.com/xJon/The-1.12.2-Pack/assets/116804099/5fd64759-e021-441b-a747-34ed7059d58a)

**Comment by xJon** [comment] 2023-09-03 18:46
If you want, you can test the patch to VintageFix that is supposed to resolve this bug: https://nightly.link/embeddedt/VintageFix/workflows/gradle/main/Package.zip (make sure to unzip it)

**Comment by andoraspalace** [comment] 2023-09-03 19:48
That Hotfix did nothing.

**Comment by xJon** [comment] 2023-09-03 20:36
@andoraspalace I am unable to reproduce your issue with that fix. Are you sure you updated the mod, by removing the old version and installing the new one?

**Comment by andoraspalace** [comment] 2023-09-03 20:47
I replaced the old vintage with "vintagefix-0.3.1-9-gd817d57.jar" **not** with the vintagefix-0.3.1-9-gd817d57-dev.jar

**Comment by xJon** [comment] 2023-09-03 20:50
@andoraspalace Can you try to download it again? There was another change since, it should be called `vintagefix-0.3.1-10-gbd4ea54.jar`.

**Comment by andoraspalace** [comment] 2023-09-03 20:59
``vintagefix-0.3.1-10-gbd4ea54.jar`` is fixing **not** everything.

If there are diffrent types of bits in one block, the glas won't be transparent anymore!

![2023-09-03_22 57 42](https://github.com/xJon/The-1.12.2-Pack/assets/116804099/ffec4050-3168-4c55-9cdb-1b78b4e0b216)

**Comment by xJon** [comment] 2023-09-03 21:09
@andoraspalace Can you try downloading again? (this time `vintagefix-0.3.1-11-g26242a5.jar`)

**Comment by andoraspalace** [comment] 2023-09-03 21:32
``vintagefix-0.3.1-11-g26242a5.jar`` is working completely fine.

Issue **solved**!

**Comment by xJon** [comment] 2023-09-03 21:37
> `vintagefix-0.3.1-11-g26242a5.jar` is working completely fine.
> 
> Issue **solved**!
> 
> Thanks for the quick solution.

Thank @embeddedt :)

**Comment by xJon** [comment] 2024-04-12 21:46
This should be resolved in `1.5.6`.

**Closed by xJon** 2024-04-12 21:46 UTC
Labels: fixed
