### ISSUE TITLE
Game crashes once i get to the moon

### ISSUE THREAD

**Issue by Evanking321** [xJon/The-1.12.2-Pack#939] opened 2024-01-28 14:07 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Crash/latest log
I think this is the log, but i dont know.
[crash-2024-01-27_21.33.05-client.txt](https://github.com/xJon/The-1.12.2-Pack/files/14076269/crash-2024-01-27_21.33.05-client.txt)

2. Is Optifine installed or any other additional mods: **yes (list) / no** 
yes
**Issue description**
Description of what help is needed.
When going to moon after the landing, when trying to get out of the rocket the game crashes as shown in the video.
https://github.com/xJon/The-1.12.2-Pack/assets/157925084/fdcb2696-1264-49b3-ad4e-2055d2bba18f

**Comment by Evanking321** [comment] 2024-01-28 15:08
Hello again! just tried now reverting to an old save, but i want to be on the save i was at when crashing, we were missing tier 1 space suits. which may be why we crash, is it possible to help me with the game files to addd suits to our players.

**Comment by xJon** [comment] 2024-01-28 15:23
This is most likely a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/908, you can manually update Extra Planets as a workaround until the next modpack update :)

**Comment by SoonerBeast17** [comment] 2024-02-11 09:53
> This is most likely a duplicate of #908, you can manually update Extra Planets as a workaround until the next modpack update :)

How do you manually update extra planets for the technic launcher?

**Comment by xJon** [comment] 2024-02-12 01:11
@SoonerBeast17 You download the new mod version: https://www.curseforge.com/minecraft/mc-mods/extraplanets/files/4756976
And replace it with the existing one in the modpack's installation folder -> `mods`

**Comment by xJon** [comment] 2024-04-12 02:07
Closing due to inactivity.

**Closed by xJon** 2024-04-12 02:07 UTC
Labels: duplicate
