### ISSUE TITLE
Lead smelts to Galena

### ISSUE THREAD

**Issue by Noobly-Walker** [xJon/The-1.12.2-Pack#870] opened 2023-04-02 09:30 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
Yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
Yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
Yes

**Information required**
1. Is the modpack crashing: No
2. Crash/latest log *link* ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): N/A
3. Is Optifine installed or any other additional mods: N/A

ThermalFoundation Lead Ore now smelts into GalacticraftPlanets Galena Ingot in a ThermalExpansion Redstone Furnace.
[Possibly caused by a fix to this bug.](https://github.com/xJon/The-1.12.2-Pack/issues/747)

**Comment by xJon** [comment] 2023-04-02 15:59
Which modpack version are you running?

**Comment by Noobly-Walker** [comment] 2023-04-02 21:44
I'm running 1.5.2. If it's fixed in 1.5.3, that means I need to get _30 to get off of the "Recommended" version and onto "Latest". Thank you.

**Comment by xJon** [comment] 2023-04-02 21:49
`1.5.4` should release this week and get pushed to recommended :)

**Comment by Noobly-Walker** [comment] 2023-04-03 01:26
Checking the latest version, it seems that Thermal Lead Ore smelts to Galactic Lead Ingot.

**Comment by xJon** [comment] 2023-04-03 04:20
Thank you for the report, I was able to reproduce the issue only on multiplayer but I understand the cause so it'll be addressed in the next update!

**Comment by xJon** [comment] 2023-04-03 04:29
There are multiple workarounds for now, but the easiest server-side would be adding these two lines to `\scripts\t1122p_changes.zs`:
```
val oreDictOreLead = <ore:oreLead>;
oreDictOreLead.remove(<galacticraftplanets:venus:8>);
```

**Comment by Noobly-Walker** [comment] 2023-04-03 04:49
_30 is trying it now, but deduplicating GC lead would probably be better in the long run. It doesn't disturb progression too much, merely allowing an early Tier 1 Battery and a few other things that would be made on Mars instead of Venus.

**Comment by xJon** [comment] 2023-04-03 04:58
Venus is supposed to be the highest tier Galacticraft area, so I'd rather keep the intended progression rather than having access to its material in the overworld.

**Comment by Noobly-Walker** [comment] 2023-04-03 05:15
Considering GC Core, perhaps, but considering all the addons, the highest tier has you going to other star systems.

**Comment by xJon** [comment] 2023-04-03 05:24
Players can always modify the modpack in ways they see fit! Nevertheless, did the workaround I shared above resolve the reported issue?

**Comment by Noobly-Walker** [comment] 2023-04-03 06:57
TBD, _30 has yet to actually restart the server.

**Comment by Noobly-Walker** [comment] 2023-04-07 22:16
I can confirm the workaround seems to work.

**Closed** 2023-04-08 00:26 UTC
Labels: fixed
