### ISSUE TITLE
game crashing bug

### ISSUE THREAD

**Issue by UNdodo** [xJon/The-1.12.2-Pack#41] opened 2019-12-08 23:48 UTC
**Basic details**
1. Are you using the latest/recommended version of the modpack without any major additional mods:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
** yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

If you have answered **no** to one of these, please correct it before posting an issue and try to reproduce the bug. If you have answered **yes** to all, please continue to fill the needed information.

**Information required**
1. Is the modpack crashing: **sort of**
2. [Please only post logs using [paste.ubuntu.com](https://paste.ubuntu.com) or [pastebin.com](https://pastebin.com/index)]: **ok**
3. Crash/latest log **link** ([Where to find](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder)): **link**
4. Is Optifine installed or any other additional mods: **yes only optifine**

**whenever i open the jei and go to a mobdrop, then open the how to get mob section it renders the game unplayble and kicks me from the server the bug works on several servers including haxeys hideout i did not try it out in singleplayer**
A clear and concise description of what the issue is.

**Comment by xJon** [comment] 2019-12-09 13:30
Please post the crash log using https://pastebin.com

**Comment by treva2512** [comment] 2019-12-10 00:35
Error EnderIO?
https://paste.dimdev.org/pibogojafi.mccrash

**Comment by xJon** [comment] 2019-12-10 04:29
@treva2512  The error usually happens when not using a legitimate launcher / Minecraft account. This is not supported by the modpack

**Comment by Furry** [comment] 2019-12-11 16:26
The issue was reported on the previous version of the pack, but I don't think that would change this.

I tested with Optifine 1.12.2 HD U F5, and couldn't reproduce this bug. I tested on HaxysHideout, as well as single-player and neither had the crash described above.

**Comment by UNdodo** [comment] 2019-12-11 16:29
^

**Comment by xJon** [comment] 2019-12-11 20:44
I'll close the issue then.
Will reopen if requested.

**Closed by xJon** 2019-12-11 20:44 UTC
Labels: missing information
