### ISSUE TITLE
Zombies not burning in sunlight 

### ISSUE THREAD

**Issue by osama1991** [xJon/The-1.12.2-Pack#918] opened 2023-10-07 00:38 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
*yes**
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
 yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no

3. Is Optifine installed or any other additional mods: no

**Describe the issue**

Zombies wont burn in sunlight, I got chased by a zombie outside in daylight. I tried spawning in zombies in creative they didnt burn. Spawned in a skeleton and it burned. This happening with anyone else?

**Comment by xJon** [comment] 2023-10-07 02:28
Caused by https://github.com/ACGaming/UniversalTweaks/issues/277, will be resolved in the next modpack update :)

**Comment by osama1991** [comment] 2023-10-07 06:06
> Caused by [ACGaming/UniversalTweaks#277](https://github.com/ACGaming/UniversalTweaks/issues/277), will be resolved in the next modpack update :)

ok, when can we expect the update? anyway to update the mod causing it manually

**Comment by xJon** [comment] 2023-10-07 07:09
@osama1991 Yes, you can manually download the updated mod version from [here](https://github.com/ACGaming/UniversalTweaks/actions/runs/6300188252) (extract the non-sources jar from the zip).

**Comment by osama1991** [comment] 2023-10-08 03:10
> @osama1991 Yes, you can manually download the updated mod version from [here](https://github.com/ACGaming/UniversalTweaks/actions/runs/6300188252) (extract the non-sources jar from the zip).

I did that but now im getting a bunch of incompatibilities
![image](https://github.com/xJon/The-1.12.2-Pack/assets/146902397/74e62624-c29f-4526-9327-88ee19f2abb7)

**Comment by xJon** [comment] 2023-10-08 17:33
@osama1991 You're right, it'd be better to use a slightly older version that still has the Zombie fix. I'd reinstall the modpack just to be sure, and then use [this](https://github.com/ACGaming/UniversalTweaks/actions/runs/6239191637) version.

**Comment by osama1991** [comment] 2023-10-09 02:27
> @osama1991 You're right, it'd be better to use a slightly older version that still has the Zombie fix. I'd reinstall the modpack just to be sure, and then use [this](https://github.com/ACGaming/UniversalTweaks/actions/runs/6239191637) version.

I havent reinstalled the modpack but it seems to be working fine now without the incompatibilities thanks

**Comment by xJon** [comment] 2024-04-12 21:49
This should be resolved in `1.5.6`.

**Closed by xJon** 2024-04-12 21:49 UTC
Labels: fixed
