### ISSUE TITLE
Missing textures from mod "Fairy Lights"

### ISSUE THREAD

**Issue by themnexurst** [xJon/The-1.12.2-Pack#709] opened 2021-08-21 18:07 UTC
The mod "Fairy lights", attempting to include sofisticated light garlands, etc. does not function correctly.
Whenever a garland, bunting or hanging light is placed the texture of the garland string and any lantern/light bulb/etc is not displayed. However, all light effects are integrated correctly (from what I saw, refer to screenshots)

I am currently using modpack version 1.3.7

![2021-08-21_20 05 31](https://user-images.githubusercontent.com/75909371/130331141-d01d783a-0f0b-4c83-b322-5c4524e56cee.png)
![2021-08-21_20 05 40](https://user-images.githubusercontent.com/75909371/130331145-7139b4c8-52dd-4d0b-81d5-0a5022d1928b.png)

**Comment by xJon** [comment] 2021-08-21 20:25
This is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/697, which is a bug in the Entity Culling mod (https://github.com/Meldexun/EntityCulling/issues/31).
> Until this gets fixed, as a workaround you can disable Entity Culling through its configuration GUI.

**Closed by xJon** 2021-08-21 20:25 UTC
Labels: duplicate
