### ISSUE TITLE
Galacticraft double Planets

### ISSUE THREAD

**Issue by Striker183** [xJon/The-1.12.2-Pack#841] opened 2022-12-02 21:54 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**yes**.

**Information required**
1. Is the modpack crashing: **no**
2. Image: *[Link (Lightshot)](https://prnt.sc/n-VO0j5jRL_i)*
3. Is Optifine installed or any other additional mods: **Yes (optifine)**

**Describe the issue**

Hello, I have explored various planets via research paper. Now these are partially displayed twice both in the list on the left (see picture) and on their orbit. It's definitely not normal, maybe it's a known bug, if not then I've successfully registered it.

Greetings, Alex

**Comment by xJon** [comment] 2022-12-02 22:17
Thanks for the report! I suspect it's caused by Planet Progression, and we also recently updated it - could you please forward the report to https://github.com/MJRLegends/Planet-Progression/issues ?

**Comment by Striker183** [comment] 2022-12-02 22:32
I forwarded it and reposted it to PlanetProgression.

**Comment by Striker183** [comment] 2022-12-02 22:48
They answer the following:

>[MJRLegends] write: "This is a Galacticraft bug, as the red ones are being incorrectly added by their new version"

**Comment by xJon** [comment] 2023-03-30 18:46
Should be fixed in version `1.5.3` of the modpack :)

**Closed by xJon** 2023-03-30 18:46 UTC
Labels: fixed
