### ISSUE TITLE
Galacticraft & Mekanism cause Server Crash

### ISSUE THREAD

**Issue by Eragonasy** [xJon/The-1.12.2-Pack#840] opened 2022-11-18 17:56 UTC
Hello xJon, there seems to be a nice bug crashing my minecraft server

Basic details
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

Information required

1. Is the modpack crashing: yes
2. Crash/latest log Crash-report https://mclo.gs/YlEPpAN
3. Is Optifine installed or any other additional mods:  no

It seems that using a Galacticraft Oxygencompressor with Mekanism Universal cables will crash the game, happened first after Pack update to 1.5.1, before it worked for 9 months through versions 1.3.0 to 1.4.1. 
Upgrade to 1.5.2 didn't fix it, im currently looking for a work around.

Info to the object:
Oxygencompressor is placed on top of a basic universal cable (Mekanism) and below a Oxygencollector. Only one Oxygencompressor exists in all dimensions

**Comment by xJon** [comment] 2022-11-18 19:12
Following these instructions, I cannot reproduce the issue either on singleplayer or on a dedicated server:
![image](https://user-images.githubusercontent.com/8945347/202784122-e7778d53-7b2f-4ce8-847a-ff7a20470099.png)

**Comment by Eragonasy** [comment] 2022-11-18 19:37
Well maybe the fault is in the Mekanism Cable then...i have 100+ Machines on that cable, mixed with its advanced/elite/ultimate form, getting its energy from huge Inductioncells. Working around didnt work till now, other versions (1.5.1, 1.5.0) have the same problem in Singleplayer/Multiplayer, 1.4.3 crashes even earlier.

**Comment by xJon** [comment] 2023-04-08 14:34
I've forwarded this to the new Mekanism repository, I don't think there's anything else I can do at this point, so I'll close this. If you want this can be reopened, and also you can post more information over https://github.com/Thorfusion/Mekanism-Community-Edition/issues/108

**Closed by xJon** 2023-04-08 14:34 UTC
Labels: can't reproduce

**Comment by xJon** [comment] 2023-10-25 20:08
@Eragonasy Can you follow up this? https://github.com/Thorfusion/Mekanism-Community-Edition/issues/108#issuecomment-1771223747
