### ISSUE TITLE
Morph "disguise" trait causes crashes with Zombie Pigmen

### ISSUE THREAD

**Issue by HugoZink** [xJon/The-1.12.2-Pack#448] opened 2020-06-12 23:51 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
**Yes**.
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
**Yes**.
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
**Yes**.

**Information required**
1. Is the modpack crashing: **Yes**
2. Crash/latest log *link*: **https://hastebin.com/ujopirazij.rb**
3. Is Optifine installed or any other additional mods: **no**

**Describe the issue**

Ever since the 1.2.0 update, entering the Nether sometimes _crashes the server._

This seems to be caused by the implementation of the "disguise" trait in Morph, which makes hostile mobs ignore you when morphed into a zombie yourself.

**Comment by xJon** [comment] 2020-06-13 17:53
Please post your logs using http://pastebin.com, as I can't view it currently.

**Comment by HugoZink** [comment] 2020-06-14 11:49
https://pastebin.com/TUm3Jhww

**Comment by xJon** [comment] 2020-06-14 17:31
Please use http://pastebin.com next time you post your game logs.
This issue is a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/262.
You're crashing due to a problematic entity, and you can try setting these two settings to true in `the-1122-pack\config\forge.cfg` **after you've backed up your save**:
```
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=true

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=true
```

**Closed by xJon** 2020-06-14 17:31 UTC
Labels: duplicate
