### ISSUE TITLE
Ender IO Travel Anchor not visible through walls

### ISSUE THREAD

**Issue by temperos** [xJon/The-1.12.2-Pack#783] opened 2022-04-17 15:40 UTC
**Basic details**
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM? ([How to check](https://www.wikihow.com/Check-Computer-RAM)):
yes
3. Are you using Java 8, 64-bit? ([How to check](https://www.wikihow.com/Determine-Java-Version)):
yes

**Information required**
1. Is the modpack crashing: no
3. Is Optifine installed or any other additional mods: no

**Describe the issue**
I placed a Travel Anchor from the Ender IO mod, named it (Base, in my case) and closed the pop-up menù.
Then I selected the Staff of travelling from the Hotbar, standing in front of it, and it highlits as it should be. Right-click teleports me.
But when i moved out from the room, with the Staff in my hand and a wall between me and the Anchor, I can't see the Anchor no more.
The "visible" option is ON, but it only works untill there are no blocks between you and the Anchor.

This bug showed up to me because I went into a mine with no worries about to get lost, due to the Anchor in my base. But when it was time to come back, I couldn't find it anywhere on the screen.

**Comment by xJon** [comment] 2022-04-17 16:14
I'm pretty sure this is caused by Entity Culling, and that Ender IO's Travel Anchors need to be blacklisted in the mod's config.

**Comment by temperos** [comment] 2022-04-17 16:55
I'm not really sure I know how to do this. Any hint?

**Comment by xJon** [comment] 2022-04-18 18:20
Whilst in-game, pause the game and press `Mod Options...` -> search for and select `Entity Culling..` -> press `Config` -> press `tileentity` -> press `skipHiddenEntityRenderingBlacklist` -> press the green `+` -> enter `enderio:tile_travel_anchor`.

**Comment by xJon** [comment] 2022-06-25 12:58
I can confirm that workaround works and it will be included by default in the next modpack update ^

**Closed** 2022-08-19 09:20 UTC
Labels: fixed
