### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by DUSTYBOY013** [xJon/The-1.12.2-Pack#468] opened 2020-07-05 19:11 UTC

**Comment by DUSTYBOY013** [comment] 2020-07-05 19:17
Everytime i warp into the nether my game crashes. Does anyone know why??

**Comment by xJon** [comment] 2020-07-06 07:53
Please post your latest log file using a [paste-tool](http://paste.ubuntu.com/).
You can find it using [this](https://github.com/xJon/The-1.12.2-Pack/blob/master/log_location.md#finding-modpack-installation-folder) guide.

**Comment by iSpookU** [comment] 2020-07-08 03:08
[crash-2020-07-07_22.56.59-server.txt](https://github.com/xJon/The-1.12.2-Pack/files/4888184/crash-2020-07-07_22.56.59-server.txt)

Im having the same issue whenever I join the nether. ^^

**Comment by xJon** [comment] 2020-07-08 05:24
Please use a paste-tool such as http://pastebin.com.

**Comment by Mishka6783** [comment] 2020-07-11 09:29
Just a heads up i have found 2 ways around this crash, If you fly though the nether portal and make sure your feet don't touch the ground till you are clear of the portal chunk this seems to help, or use mystcraft linking books after the first visit. simply delete your nether dim folder from your save file and then re enter the nether and use linking books.

**Comment by iSpookU** [comment] 2020-07-11 22:58
Yeah I found a way to fix it myself. It was just a ticking entity that I needed to remove. Thanks anyway.

**Comment by MonsieurGilbert** [comment] 2020-07-18 13:31
Hello, i have the same problem with a ticking entity in the nether.
This happens with me when i die in the nether as a morph, then go back in again into the nether.
(might it be the skeletons spawning from the gravestone?)

Here is the crash log from my server:
pastebin.com/qBqk1nyd

**Comment by calvinloveland** [comment] 2020-07-19 22:21
I believe I've hit the same issue. Died in the nether close to the nether portal. Server crashed when I went through the portal and server crashes every time I've tried to join again. Will work on uploading my crash report

**Comment by xJon** [comment] 2020-07-22 11:05
I was not able to reproduce the issue with what @MonsieurGilbert described. Due to the lack of a way to reproduce this issue in a different way, it will be marked as a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/262.

**Closed by xJon** 2020-07-22 11:05 UTC
Labels: duplicate
