### ISSUE TITLE
Fall damage is still taken even when using modular power suit parachute

### ISSUE THREAD

**Issue by Raxcental** [xJon/The-1.12.2-Pack#413] opened 2020-05-22 19:02 UTC
1. Are you using a legitimate launcher and Minecraft account:
yes
2. Are you using a computer with 8GB or more of RAM?:
yes
3. Are you using Java 8, 64-bit?:
yes

1. Is the modpack crashing: no
2. Crash/latest log: NA
3. Is Optifine installed or any other additional mods: no

A clear and concise description of what the issue is:

I installed the parachute module into my modular power suit chest. I am still taking fall damage and dying even when I'm holding shift while falling.

**Comment by Raxcental** [comment] 2020-05-26 19:05
A good fallback is installing the shock absorber module and maxing it out. As long as your suit is charged up, you won't die.

**Comment by xJon** [comment] 2020-05-26 19:31
I'm not sure if we're doing something or not, so I've forwarded it onto an issue already posted in the mod's repo.
Now I realize this is actually a duplicate of https://github.com/xJon/The-1.12.2-Pack/issues/365.
For now I'll close this, as there's a workaround anyway. Thank you for reporting!

**Closed by xJon** 2020-05-26 19:31 UTC
Labels: duplicate

**Comment by Raxcental** [comment] 2020-05-26 19:32
No problem! I figure if I report anything I find, it will either get fixed or a workaround will be found. Good to know I'm not the only one experiencing the issue though.
